# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/brett/Thesis/Vivado_WS/sha256test/sha256test.cache/wt [current_project]
set_property parent.project_path /home/brett/Thesis/Vivado_WS/sha256test/sha256test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/brett/Thesis/Vivado_WS/ip_repo/axi_mm2s_converter_1.0
  /home/brett/Thesis/Vivado_WS/sha256
} [current_project]
set_property ip_output_repo /home/brett/Thesis/Vivado_WS/sha256test/sha256test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/brett/Thesis/Vivado_WS/sha256test/sha256test.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files /home/brett/Thesis/Vivado_WS/sha256test/sha256test.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/brett/Thesis/Vivado_WS/sha256test/sha256test.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/brett/Thesis/Vivado_WS/sha256test/sha256test.srcs/sources_1/bd/design_1/ip/design_1_sha256_0_0/constraints/sha256_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brett/Thesis/Vivado_WS/sha256test/sha256test.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_1/design_1_rst_ps7_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/brett/Thesis/Vivado_WS/sha256test/sha256test.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_1/design_1_rst_ps7_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all /home/brett/Thesis/Vivado_WS/sha256test/sha256test.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_1/design_1_rst_ps7_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brett/Thesis/Vivado_WS/sha256test/sha256test.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/brett/Thesis/Vivado_WS/sha256test/sha256test.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brett/Thesis/Vivado_WS/sha256test/sha256test.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brett/Thesis/Vivado_WS/sha256test/sha256test.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/brett/Thesis/Vivado_WS/sha256test/sha256test.srcs/sources_1/bd/design_1/design_1.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
